### ISSUE TITLE
NoSuchMethodError: org.openstreetmap.josm.tools.Geometry.isNodeInsideMultiPolygon

### ISSUE THREAD

**Issue by mkyral** [mkyral/josm-tracer#27]
```
=== REPORTED CRASH DATA ===
BugReportExceptionHandler#handleException:
No data collected.

Warning issued by: BugReportExceptionHandler#handleException

=== STACK TRACE ===
Thread: AWT-EventQueue-0 (16) of main
java.lang.NoSuchMethodError: org.openstreetmap.josm.tools.Geometry.isNodeInsideMultiPolygon(Lorg/openstreetmap/josm/data/osm/Node;Lorg/openstreetmap/josm/data/osm/Relation;Lorg/openstreetmap/josm/tools/Predicate;)Z
    at org.openstreetmap.josm.plugins.tracer.connectways.WayEditor.useNonEditedAreasContainingPoint(WayEditor.java:559)
    at org.openstreetmap.josm.plugins.tracer.modules.lpis.LpisModule$LpisTracerTask.getObjectToRetrace(LpisModule.java:379)
    at org.openstreetmap.josm.plugins.tracer.modules.lpis.LpisModule$LpisTracerTask.createTracedPolygonImpl(LpisModule.java:215)
    at org.openstreetmap.josm.plugins.tracer.TracerModule$AbstractTracerTask$6.run(TracerModule.java:347)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by pschonmann** [comment]
```
{{{
URL:http://josm.openstreetmap.de/svn/trunk
Repository:UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Last:Changed Date: 2016-08-11 21:54:24 +0200 (Thu, 11 Aug 2016)
Build-Date:2016-08-11 22:36:05
Revision:10786
Relative:URL: ^/trunk

Identification: JOSM/1.5 (10786 cs) Windows 10 64-Bit
Memory Usage: 1712 MB / 3637 MB (148 MB allocated, but free)
Java version: 1.8.0_102-b14, Oracle Corporation, Java HotSpot(TM) 64-Bit Server VM
Dataset consistency test: No problems found

Plugins:
+ BuildingGeneralization (1010)
+ Mapillary (32796)
+ OpeningHoursEditor (32699)
+ Tracer-testing (1457538387)
+ apache-commons (32699)
+ apache-http (32699)
+ auto_tools (1468620578)
+ buildings_tools (32796)
+ download_along (32730)
+ editgpx (32699)
+ ejml (32680)
+ geotools (32813)
+ imagery_offset_db (32796)
+ imageryadjust (32699)
+ jts (32699)
+ opendata (32811)
+ pointInfo (32796)
+ turnlanes-tagging (1470950886)
+ turnrestrictions (32796)
+ utilsplugin2 (32815)
+ waydownloader (32699)
+ waypoint_search (32699)
+ wikipedia (32829)

Tagging presets:
+ https://josm.openstreetmap.de/josmfile?page=Presets/Communication_Towers&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Presets/Czech_hiking&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Presets/SentieriItaliani&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Presets/NewTags&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Presets/Trees&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Presets/Crafts&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Presets/CommonKeyboardShortcuts&zip=1

Map paint styles:
- https://github.com/simon04/coloured-addresses.mapcss/raw/master/dist/coloured-addresses.mapcss
- https://josm.openstreetmap.de/josmfile?page=Styles/Fixme&zip=1

Validator rules:
+ https://josm.openstreetmap.de/josmfile?page=Rules/CzechRepublicAddressSystem&zip=1
+ https://raw.githubusercontent.com/stefan-a-bauer/josm-validators/master/mtb.validator.mapcss

Last errors/warnings:
- W: java.io.IOException: Attribution is not loaded yet
- W: java.io.IOException: Attribution is not loaded yet
- W: java.io.IOException: Attribution is not loaded yet
- W: java.io.IOException: Attribution is not loaded yet
- W: java.io.IOException: Attribution is not loaded yet
- W: java.io.IOException: Attribution is not loaded yet
- E: java.lang.NoSuchMethodError: org.openstreetmap.josm.tools.Geometry.isNodeInsideMultiPolygon(Lorg/openstreetmap/josm/data/osm/Node;Lorg/openstreetmap/josm/data/osm/Relation;Lorg/openstreetmap/josm/tools/Predicate;)Z
- E: java.lang.NoSuchMethodError: org.openstreetmap.josm.tools.Geometry.isNodeInsideMultiPolygon(Lorg/openstreetmap/josm/data/osm/Node;Lorg/openstreetmap/josm/data/osm/Relation;Lorg/openstreetmap/josm/tools/Predicate;)Z
- E: java.lang.NoSuchMethodError: org.openstreetmap.josm.tools.Geometry.isNodeInsideMultiPolygon(Lorg/openstreetmap/josm/data/osm/Node;Lorg/openstreetmap/josm/data/osm/Relation;Lorg/openstreetmap/josm/tools/Predicate;)Z
- E: java.lang.NoSuchMethodError: org.openstreetmap.josm.tools.Geometry.isNodeInsideMultiPolygon(Lorg/openstreetmap/josm/data/osm/Node;Lorg/openstreetmap/josm/data/osm/Relation;Lorg/openstreetmap/josm/tools/Predicate;)Z


=== REPORTED CRASH DATA ===
BugReportExceptionHandler$BugReporterThread#askForBugReport:
No data collected.

=== STACK TRACE ===
Thread: AWT-EventQueue-0 (19) of main
java.lang.NoSuchMethodError: org.openstreetmap.josm.tools.Geometry.isNodeInsideMultiPolygon(Lorg/openstreetmap/josm/data/osm/Node;Lorg/openstreetmap/josm/data/osm/Relation;Lorg/openstreetmap/josm/tools/Predicate;)Z
	at org.openstreetmap.josm.plugins.tracer.connectways.WayEditor.useNonEditedAreasContainingPoint(WayEditor.java:559)
	at org.openstreetmap.josm.plugins.tracer.modules.lpis.LpisModule$LpisTracerTask.getObjectToRetrace(LpisModule.java:379)
	at org.openstreetmap.josm.plugins.tracer.modules.lpis.LpisModule$LpisTracerTask.createTracedPolygonImpl(LpisModule.java:215)
	at org.openstreetmap.josm.plugins.tracer.TracerModule$AbstractTracerTask$6.run(TracerModule.java:347)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

```

**Comment by mkyral** [comment]
No asi je načase se na to pořádně mrknout. Respektive už jsem koukal, ale zatím si nejsem jist správným řešením.

**Comment by mkyral** [comment]
Tak jsem to včera zkoumal a vše se zdálo v pořádku. Pak jsem to zkompiloval nejnovější verzí javy 8 a najednou to začalo fungovat. Ještě to budu chvíli testovat a pak pustím novou verzi.

**Comment by mkyral** [comment]
Nahrál jsem novou verzi zkompilovanou pod java 8. Vyzkoušej prosím, za vše funguje jak má.

**Comment by mkyral** [comment]
Tak už to je nějakou dobu nasazeno a nikdo si nestěžuje, takže asi opraveno.
