### ISSUE TITLE
JOSM ver. 11636 a 11639 - NoSuchMethodError: org.openstreetmap.josm.gui.conflict.tags.TagConflictResolutionUtil.combineTigerTags

### ISSUE THREAD

**Issue by majkaz** [mkyral/josm-tracer#35]
Nezkoumala jsem jiné verze, ale JOSM ve verzi 11636 a 11639 vyhazuje chybu při trasování podle RUIAN - budovy, trasování neproběhne. RUIAN - parcely běhá normálně, LPis jsem nezkoumala. Naprosto stejná instalace, jen při použití JOSM verze 11526 (tested) běží normálně.

Posílám spíš jen jako varování. Pokud bude třeba výpis chyby, pošlu.

**Comment by mkyral** [comment]
Díky za info. Koukám. že zase vylepšovali něco uvnitř :-(

```
2017-02-27 18:33:03.206 SEVERE: Handled by bug report queue: java.lang.NoSuchMethodError: org.openstreetmap.josm.gui.conflict.tags.TagConflictResolutionUtil.combineTigerTags(Lorg/openstreetmap/josm/data/osm/TagCollection;)V
java.lang.NoSuchMethodError: org.openstreetmap.josm.gui.conflict.tags.TagConflictResolutionUtil.combineTigerTags(Lorg/openstreetmap/josm/data/osm/TagCollection;)V
        at org.openstreetmap.josm.plugins.tracer.CombineTagsResolver.launchIfNecessary(CombineTagsResolver.java:84)
        at org.openstreetmap.josm.plugins.tracer.modules.building.BuildingTracerModule$BuildingTracerTask.tagTracedObject(BuildingTracerModule.java:358)
        at org.openstreetmap.josm.plugins.tracer.modules.building.BuildingTracerModule$BuildingTracerTask.createTracedPolygonImpl(BuildingTracerModule.java:245)
        at org.openstreetmap.josm.plugins.tracer.TracerModule$AbstractTracerTask$6.run(TracerModule.java:348)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
        at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
        at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
        at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
        at java.awt.Dialog.show(Dialog.java:1084)
        at java.awt.Component.show(Component.java:1671)
        at java.awt.Component.setVisible(Component.java:1623)
        at java.awt.Window.setVisible(Window.java:1014)
        at java.awt.Dialog.setVisible(Dialog.java:1005)
        at org.openstreetmap.josm.gui.progress.PleaseWaitProgressMonitor.lambda$doBeginTask$3(PleaseWaitProgressMonitor.java:194)
        at org.openstreetmap.josm.gui.progress.PleaseWaitProgressMonitor.lambda$doInEDT$0(PleaseWaitProgressMonitor.java:60)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by mkyral** [comment]
Tak naštěstí došlo jen k přejmenování.
