### ISSUE TITLE
Ojedinělá chyba při trasování budov podle RUIAN

### ISSUE THREAD

**Issue by majkaz** [mkyral/josm-tracer#36]
Plugin mi normálně běží, jen při přetrasování několika budov mi vyhodil následující chybu:
---
{{{
URL:http://josm.openstreetmap.de/svn/trunk
Repository:UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Last:Changed Date: 2017-03-05 23:29:19 +0100 (Sun, 05 Mar 2017)
Build-Date:2017-03-06 02:33:52
Revision:11694
Relative:URL: ^/trunk

Identification: JOSM/1.5 (11694 en) Windows 7 32-Bit
Memory Usage: 494 MB / 494 MB (61 MB allocated, but free)
Java version: 1.8.0_101-b13, Oracle Corporation, Java HotSpot(TM) Client VM
Dataset consistency test: No problems found

Plugins:
+ CommandLine (33026)
+ FastDraw (33004)
+ OpeningHoursEditor (33004)
+ PicLayer (33148)
+ Tracer-testing (1488388300)
+ apache-commons (32994)
+ areaselector (1478814827)
+ auto_tools (1479831713)
+ buildings_tools (33004)
+ continuosDownload (53)
+ contourmerge (1030)
+ ejml (32680)
+ geojson (52)
+ geotools (33042)
+ imagery_offset_db (33004)
+ imageryadjust (33004)
+ importvec (33088)
+ jts (32699)
+ log4j (32699)
+ opendata (33156)
+ pointInfo (33131)
+ poly (33004)
+ reltoolbox (33088)
+ reverter (33088)
+ tageditor (33021)
+ terracer (33088)
+ todo (30000)
+ turnlanes-tagging (254)
+ utilsplugin2 (33124)

Tagging presets:
+ .\presets\HOT.xml
+ https://josm.openstreetmap.de/josmfile?page=Presets/Light_sources&zip=1
+ http://zibi.openstreetmap.org.pl/kendzi/k/Simple3dPreset/s3db-preset.zip
+ https://josm.openstreetmap.de/josmfile?page=Presets/BuildingPreset&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Presets/Playground_Equipment&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Presets/ParkingLanes&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Presets/Simple_Indoor_Tagging&zip=1
+ https://raw.githubusercontent.com/species/josm-preset-wheelchair/master/sidewalks_kerbs.xml

Map paint styles:
- https://github.com/hotosm/HDM-JOSM-style/archive/master.zip
- https://josm.openstreetmap.de/josmfile?page=Styles/NoFeature&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Modified&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/HiDPISupport&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Highway_Nodes&zip=1
- styly\HOT-Osm-Validation-master\HOT-Validate.mapcss
- https://josm.openstreetmap.de/josmfile?page=Styles/Surface-DataEntry&zip=1
+ https://github.com/gmgeo/osmic-josm-style/archive/master.zip
- https://josm.openstreetmap.de/josmfile?page=Styles/Landcover&zip=1
- https://www.dropbox.com/s/qo3ai47fpv241jf/Styles_Fixme_and_Notes.zip?raw=1
- styly\HOT-Osm-Validation-master\building.mapcss
+ https://josm.openstreetmap.de/josmfile?page=Styles/NewHighwayColors&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Sidewalks&zip=1
+ https://josm.openstreetmap.de/josmfile?page=Styles/Lane_and_Road_Attributes&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Enhanced_Lane_and_Road_Attributes&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Lane_features&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Lit&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/LitObjects&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/light_source&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/DestinationSignRelation&zip=1
- https://raw.githubusercontent.com/species/josm-preset-traffic_sign_direction/master/direction.mapcss
- http://www.freietonne.de/ft_icons/josm/FreieTonne_rules_presets_zip.php
- https://github.com/bastik/mapcss-tools/raw/osm/mapnik2mapcss/osm-results/mapnik.zip
- https://github.com/GlassOceanos/indoor-JOSM-style/archive/master.zip
- https://josm.openstreetmap.de/josmfile?page=Styles/Maxspeed&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/NewParkingFeatures&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/ParkingLanes&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/ShowID&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/MaxspeedIcons&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/Surface&zip=1
- https://josm.openstreetmap.de/josmfile?page=Styles/TreeCrownDiameter&zip=1
+ styly\HOT-Osm-Validation-master\building_3D.mapcss
- styly\levels.mapcss
- T:\modified
- T:\modified.mapcss
- T:\josmfile
- styly\tasks.mapcss
- styly\buildings_wireframe.mapcss
- styly\modified.mapcss

Last errors/warnings:
- W: Unable to convert property object-z-index to type class java.lang.Float: found RelativeFloat{val=1.0} of type class org.openstreetmap.josm.gui.mappaint.mapcss.Instruction$RelativeFloat!
- E: Handled by bug report queue: java.lang.IllegalStateException: Tag collection does not include the selected value '5    .. /traced/'.
- W: stavebni_objekt.pocet_podlazi:: java.lang.ClassCastException: javax.json.JsonValue$1 cannot be cast to javax.json.JsonString
- W: stavebni_objekt.pocet_bytu:: java.lang.ClassCastException: javax.json.JsonValue$1 cannot be cast to javax.json.JsonString
- W: stavebni_objekt.dokonceni:: java.lang.ClassCastException: javax.json.JsonValue$1 cannot be cast to javax.json.JsonString
- W: nahlaseny_problem:: java.lang.IllegalArgumentException: No value for nahlaseny_problem
- W: parcela.zpusob_vyuziti:: java.lang.ClassCastException: javax.json.JsonValue$1 cannot be cast to javax.json.JsonString
- W: ulice:: java.lang.IllegalArgumentException: No value for ulice
- E: Handled by bug report queue: java.lang.IllegalStateException: Tag collection does not include the selected value '3    .. /osm/'.
- E: Handled by bug report queue: java.lang.IllegalStateException: Tag collection does not include the selected value '5    .. /traced/'.

=== REPORTED CRASH DATA ===
BugReportExceptionHandler#handleException:
No data collected.

Warning issued by: BugReportExceptionHandler#handleException

=== STACK TRACE ===
Thread: AWT-EventQueue-0 (17) of main
java.lang.IllegalStateException: Tag collection does not include the selected value '5    .. /traced/'.
	at org.openstreetmap.josm.gui.conflict.tags.MultiValueResolutionDecision.keepOne(MultiValueResolutionDecision.java:114)
	at org.openstreetmap.josm.gui.conflict.tags.TagConflictResolverModel.setValueAt(TagConflictResolverModel.java:179)
	at javax.swing.JTable.setValueAt(Unknown Source)
	at javax.swing.JTable.editingStopped(Unknown Source)
	at javax.swing.AbstractCellEditor.fireEditingStopped(Unknown Source)
	at org.openstreetmap.josm.gui.conflict.tags.MultiValueCellEditor.lambda$new$0(MultiValueCellEditor.java:125)
	at javax.swing.JComboBox.fireItemStateChanged(Unknown Source)
	at javax.swing.JComboBox.selectedItemChanged(Unknown Source)
	at javax.swing.JComboBox.contentsChanged(Unknown Source)
	at javax.swing.AbstractListModel.fireContentsChanged(Unknown Source)
	at javax.swing.DefaultComboBoxModel.setSelectedItem(Unknown Source)
	at javax.swing.JComboBox.setSelectedItem(Unknown Source)
	at javax.swing.JComboBox.setSelectedIndex(Unknown Source)
	at javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at javax.swing.plaf.basic.BasicComboPopup$1.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.awt.Dialog.show(Unknown Source)
	at java.awt.Component.show(Unknown Source)
	at java.awt.Component.setVisible(Unknown Source)
	at java.awt.Window.setVisible(Unknown Source)
	at java.awt.Dialog.setVisible(Unknown Source)
	at org.openstreetmap.josm.gui.conflict.tags.CombinePrimitiveResolverDialog.setVisible(CombinePrimitiveResolverDialog.java:374)
	at org.openstreetmap.josm.plugins.tracer.CombineTagsResolver.launchIfNecessary(CombineTagsResolver.java:102)
	at org.openstreetmap.josm.plugins.tracer.modules.building.BuildingTracerModule$BuildingTracerTask.tagTracedObject(BuildingTracerModule.java:370)
	at org.openstreetmap.josm.plugins.tracer.modules.building.BuildingTracerModule$BuildingTracerTask.createTracedPolygonImpl(BuildingTracerModule.java:245)
	at org.openstreetmap.josm.plugins.tracer.TracerModule$AbstractTracerTask$6.run(TracerModule.java:348)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.awt.Dialog.show(Unknown Source)
	at java.awt.Component.show(Unknown Source)
	at java.awt.Component.setVisible(Unknown Source)
	at java.awt.Window.setVisible(Unknown Source)
	at java.awt.Dialog.setVisible(Unknown Source)
	at org.openstreetmap.josm.gui.progress.PleaseWaitProgressMonitor.lambda$doBeginTask$3(PleaseWaitProgressMonitor.java:201)
	at org.openstreetmap.josm.gui.progress.PleaseWaitProgressMonitor.lambda$doInEDT$0(PleaseWaitProgressMonitor.java:67)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
}}}
---
Jedná se o budovu osm id: 384421219, pointinfo dává následující tagy:
"ref:ruian:building"="48387053"
"building"="warehouse"
"building:ruian:type"="12"
"source"="cuzk:ruian"

Ostatní běží normálně, trasovala jsem těch budov dnes spoustu před i po. Prosím o prohlédnutí, zda je to jen nějaký nestandard v datech, nebo je to nějaká skrytá chyba.

**Comment by mkyral** [comment]
Díky za report, zkusím si na to večer nebo zítra vzpomenout. Ale je divné, odkud se vzala hodnota "5", když PointInfo ukazuje "12".

**Comment by mkyral** [comment]
To jsem blázen. Teď to zkouším a vše funguje jak má. Můžu se zeptat, jak přesně jsi postupovala?

**Comment by majkaz** [comment]
Ahoj, řekla bych problém lze zavřít, dnes mi to vyhodilo naprosto normální industrial x warehouse, lze vybrat...

Jinak postup byl naprosto standardní, jako vše okolo - klasicky ťuknout do objektu, na pozadí se stáhla data, vyskočila tabulka s těmi hodnotami (osm  x traced), po vybrání jakékoli to zahlásilo tuhle chybu, ale normálně vše pokračovalo dál, jen tahle hala se nedala trasovat. Pokud jsem pokračovala na další objekty, vše v pořádku a ty okolní domy se natrasovaly. Po vrácení zpět k téhle hale se znovu stáhla na pozadí data a znovu to vyhodilo přesně tuhle chybu. Dělal to ještě jeden dům v tomhle okolí, minimálně v rozmezí cca 20 minut před nahlášením to bylo naprosto přesně replikovatelné.

Skoro bych řekla, že dočasně byl problém v datech u těchhle dvou objektů a plugin s tím neměl co dělat, když v jiné chvíli vše běží normálně.

**Comment by mkyral** [comment]
No možná to bude nějaká mimořádně záludná chyba, Kdybys na ni zase někdy narazila a všimla si něčeho dalšího, tak to zase otevři.
