### ISSUE TITLE
java.lang.IllegalArgumentException: Multipolygon musí obsahovat klíč type=multipolygon

### ISSUE THREAD

**Issue by mkyral** [mkyral/josm-tracer#42]
Při trasování polygonů LPIS mi JOSM padá při trasování původního polygonu ID 44326722
https://openstreetmap.cz/#map=18/50.18716/15.71554&layers=dL

výpis hlášky JOSM:

```
{{{
URL:http://josm.openstreetmap.de/svn/trunk
Repository:UUID: 0c6e7542-c601-0410-84e7-c038aed88b3b
Last:Changed Date: 2017-08-04 00:31:45 +0200 (Fri, 04 Aug 2017)
Build-Date:2017-08-04 01:31:40
Revision:12567
Relative:URL: ^/trunk

Identification: JOSM/1.5 (12567 cs) Windows 7 64-Bit
OS Build number: Windows 7 Ultimate (7601)
Memory Usage: 613 MB / 989 MB (183 MB allocated, but free)
Java version: 1.8.0_31-b13, Oracle Corporation, Java HotSpot(TM) Client VM
Screen: \Display0 1280x1024
Maximum Screen Size: 1280x1024
Dataset consistency test: No problems found

Plugins:
+ Tracer (33004)
+ Tracer-testing (1491846265)
+ Tracer2 (33004)
+ buildings_tools (33004)
+ ejml (32680)
+ geotools (33380)
+ jts (32699)
+ pointInfo (33131)
+ reverter (33088)

Last errors/warnings:
- W: Nemohu najít podporovanou projekci pro vrstvu ortofoto. Používám EPSG:3857.
- W: Nemohu najít podporovanou projekci pro vrstvu ortofoto. Používám EPSG:3857.
- W: Konflikt v datech - <html>Tato relace byla změněna mimo editor.<br>Nemůžete aplikovat změny a pokračovat v editaci.<br><br>Chcete vytvořit konflikt a uzavřít editor?</html>
- E: Handled by bug report queue: java.lang.IllegalArgumentException: Multipolygon musí obsahovat klíč type=multipolygon
- E: Handled by bug report queue: java.lang.IllegalArgumentException: Multipolygon musí obsahovat klíč type=multipolygon
- E: Handled by bug report queue: java.lang.IllegalArgumentException: Multipolygon musí obsahovat klíč type=multipolygon


=== REPORTED CRASH DATA ===
BugReportExceptionHandler#handleException:
No data collected.

Warning issued by: BugReportExceptionHandler#handleException

=== STACK TRACE ===
Thread: AWT-EventQueue-0 (17) of main
java.lang.IllegalArgumentException: Multipolygon musí obsahovat klíč type=multipolygon
    at org.openstreetmap.josm.plugins.tracer.connectways.EdMultipolygon.setKeys(EdMultipolygon.java:257)
    at org.openstreetmap.josm.plugins.tracer.modules.lpis.LpisModule$LpisTracerTask.tagTracedObject(LpisModule.java:373)
    at org.openstreetmap.josm.plugins.tracer.modules.lpis.LpisModule$LpisTracerTask.createTracedPolygonImpl(LpisModule.java:275)
    at org.openstreetmap.josm.plugins.tracer.TracerModule$AbstractTracerTask$6.run(TracerModule.java:347)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$500(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)
}}}
```

**Comment by mkyral** [comment]
Způsobuje to tag `type=orchard` na way.

```
landuse=farmland
source=uhul:ortofoto
type=orchard
```
