### ISSUE TITLE
Tracer padá v JOSM 13917 (latest)

### ISSUE THREAD

**Issue by majkaz** [mkyral/josm-tracer#44]
Prosím o prověření - v JOSM 13917 (staženo dnes, 11.06.2018, jako latest) plugin padá při trasování budovy podle RUIAN.
Pokud JOSM spustím v naprosto stejném stavu (pluginy apod.), jen ve verzi tested, natrasování běží bez problému.
Konkrétní budova - Olešnice 14, PSČ 37331, RUIAN id: 90775651

`=== STACK TRACE ===
Thread: AWT-EventQueue-0 (17) of main
java.lang.NoSuchMethodError: org.openstreetmap.josm.data.osm.BBox.<init>(Lorg/openstreetmap/josm/data/osm/Way;)V
	at org.openstreetmap.josm.plugins.tracer.connectways.EdWay.getBBox(EdWay.java:244)
	at org.openstreetmap.josm.plugins.tracer.modules.building.BuildingTracerModule$BuildingTracerTask.checkInsideDataSourceBounds(BuildingTracerModule.java:442)
	at org.openstreetmap.josm.plugins.tracer.modules.building.BuildingTracerModule$BuildingTracerTask.createTracedPolygonImpl(BuildingTracerModule.java:217)
	at org.openstreetmap.josm.plugins.tracer.TracerModule$AbstractTracerTask$6.run(TracerModule.java:351)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.WaitDispatchSupport$2.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.awt.WaitDispatchSupport$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(Unknown Source)
	at java.awt.Dialog.show(Unknown Source)
	at java.awt.Component.show(Unknown Source)
	at java.awt.Component.setVisible(Unknown Source)
	at java.awt.Window.setVisible(Unknown Source)
	at java.awt.Dialog.setVisible(Unknown Source)
	at org.openstreetmap.josm.gui.progress.swing.PleaseWaitProgressMonitor.lambda$doBeginTask$3(PleaseWaitProgressMonitor.java:256)
	at org.openstreetmap.josm.gui.progress.swing.PleaseWaitProgressMonitor.lambda$doInEDT$0(PleaseWaitProgressMonitor.java:114)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
}}}`

**Comment by mkyral** [comment]
Jojo, zas tam dělají nějaké změny. A zatím nevím co s tím :-(

**Comment by mkyral** [comment]
Čistě teoreticky fixnuto v c56add65c1fcba24413bbedcebffbe7e844727d1
Ale může tam toho být více.
