### ISSUE TITLE
Chyba traceru, latest JOSM

### ISSUE THREAD

**Issue by majkaz** [mkyral/josm-tracer#46]
Před chvílí stažený JOSM-latest, Revision:15017, chyba při použití všech částí (Ruian, Ruian-Lands, LPis).
Zahlédla jsem, že u jiných pluginů minulý týden naskakoval patch - nezměnilo se někde nějaké volání?

=== STACK TRACE ===
Thread: AWT-EventQueue-0 (18) of main
java.lang.NoSuchMethodError: org.openstreetmap.josm.data.osm.OsmPrimitive.getFilteredList(Ljava/util/Collection;Ljava/lang/Class;)Ljava/util/List;
	at org.openstreetmap.josm.plugins.tracer.connectways.AreaPredicate.evaluate(AreaPredicate.java:69)
	at org.openstreetmap.josm.plugins.tracer.connectways.WayEditor.useNonEditedAreasContainingPoint(WayEditor.java:570)
	at org.openstreetmap.josm.plugins.tracer.modules.building.BuildingTracerModule$BuildingTracerTask.getObjectToRetrace(BuildingTracerModule.java:391)
	at org.openstreetmap.josm.plugins.tracer.modules.building.BuildingTracerModule$BuildingTracerTask.createTracedPolygonImpl(BuildingTracerModule.java:186)
	at org.openstreetmap.josm.plugins.tracer.TracerModule$AbstractTracerTask$6.run(TracerModule.java:352)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.awt.Dialog.show(Dialog.java:1084)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at org.openstreetmap.josm.gui.progress.swing.PleaseWaitProgressMonitor.lambda$doBeginTask$3(PleaseWaitProgressMonitor.java:255)
	at org.openstreetmap.josm.gui.progress.swing.PleaseWaitProgressMonitor.lambda$doInEDT$0(PleaseWaitProgressMonitor.java:113)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
}}}

**Comment by mkyral** [comment]
Ahoj,
vypadá to že ano. Mrknu na to večer. Snad to nebude až takový velký problém.
